#!/bin/bash

name=${1:-rebul}

if [ ! "$SIMPLETON_REPO" ]; then
  echo "You must set SIMPLETON_REPO env var to your workspace folder before running this." >&2
  exit 1
fi

if [ ! "$SIMPLETON_HOME" ]; then
  echo "You must set SIMPLETON_HOME env var to your workspace folder before running this." >&2
  exit 1
fi

if [ ! "$SIMPLETON_WORKSPACE" ]; then
  echo "You must set SIMPLETON_WORKSPACE env var to your workspace folder before running this." >&2
  exit 1
fi

set -x
docker run -it --rm -u $UID --name $name -e COLUMNS=$COLUMNS \
  -v $SIMPLETON_REPO:/simpleton \
  -v $SIMPLETON_REPO/../rebul:/rebul \
  -v $SIMPLETON_HOME:/home \
  -v $SIMPLETON_WORKSPACE:/work \
  -e USER=$USER rebul
set +x
