#!/bin/bash

if [ ! "$SIMPLETON_WORKSPACE" ]; then
  echo "You must set SIMPLETON_WORKSPACE env var to your workspace folder before running this." >&2
  exit 1
fi

if [ ! "$SIMPLETON_HOME" ]; then
  echo "You must set SIMPLETON_HOME env var to a folder before running this." >&2
  exit 1
fi

set -x
docker run -it --rm -u $UID --name rebul -v $SIMPLETON_WORKSPACE:/work -v $SIMPLETON_HOME:/home -e USER=$USER rebul
set +x
