#!/bin/bash

if [ "${project:-}" ]; then
  projects="$project"
fi

if [ "${service:-}" ]; then
  services="$service"
fi

if [ "${env:-}" ]; then
  envs="$env"
  if [ "$env" == e3 ]; then
    envs="e30 e31 e32"
  fi
fi

if [ "${operation:-}" ]; then
  operations="$operation"
fi

if [ "${function:-}" ]; then
  functions="$function"
fi

if [ "${paas:-}" ]; then
  paass="$paas"
fi

if [ "${pod:-}" ]; then
  pods="$pod"
fi

if [ "${external:-}" ]; then
  externals="$external"
fi

if [ "${host:-}" ]; then
  hosts="$host"
fi
