#!/bin/bash

# sets os to the system identification string 
unset identify_system
identify_system() {
if [ -f /etc/debian_version ]; then
  os="linux debian $(uname -r)"
elif [ -f /etc/alpine-release ]; then
  os="linux alpine $(</etc/alpine-release)"
elif [ "$(uname -s)" == Darwin ]; then
  os="mac osx $(uname -r)"
else
  echo "I couldn't identify this system: $(uname -s)" >&2
  return 1
fi
}

unset system_matches
system_matches() {
  identify_system || return 1
  [[ "$os" == "${1}"* ]] && return 0
  echo "[$os] doesn't match [$1]*"
  return 1
}

