#!/bin/bash                        # intended to be sourced from other scripts
# provides functions to url encode and decode strings








type -t url_encode >/dev/null && return 0
url_encode() {

  local length="${#1}" result
  for (( i = 0; i < length; i++ )); do
    local c="${1:i:1}"
    case $c in
      [a-zA-Z0-9.~_-]) 
        result+=$(printf "$c")
        ;;
      *) 
        result+="%$(echo -n "$c" | xxd -u -p -c1)"
        ;;
    esac
  done

  echo -n $result

}

url_decode() {
  local url_encoded="${1//+/ }"
  printf '%b' "${url_encoded//%/\\x}"
}
